"""Shared onboarding I/O — interactive prompts + the airen.yaml renderer.

Used by both the manual wizard (airen.run_onboard) and the agentic onboarding
flow (airen.onboarding.agent). Keeping these here means the two paths emit
byte-identical YAML and share one set of prompt semantics.
"""

from __future__ import annotations

import yaml

# ───────────────────────────────────────────────────────────────────────
#  Prompt helpers — all tolerant of empty input (→ default)
# ───────────────────────────────────────────────────────────────────────
def ask(prompt: str, default: str | None = None) -> str | None:
    """Free-text prompt. Returns the default (which may be None) on empty input."""
    suffix = f" [{default}]" if default not in (None, "") else ""
    raw = input(f"  {prompt}{suffix}: ").strip()
    return default if raw == "" else raw


def ask_required(prompt: str, default: str | None = None) -> str:
    """Like ask, but loops until a non-empty value is given."""
    while True:
        val = ask(prompt, default)
        if val:
            return val
        print("    ↳ this one is required.")


def ask_bool(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    raw = input(f"  {prompt} [{d}]: ").strip().lower()
    if raw == "":
        return default
    return raw in ("y", "yes", "true", "1")


def ask_float(prompt: str, default: float) -> float:
    while True:
        raw = input(f"  {prompt} [{default}]: ").strip()
        if raw == "":
            return default
        try:
            return float(raw)
        except ValueError:
            print("    ↳ enter a number.")


def ask_int(prompt: str, default: int) -> int:
    while True:
        raw = input(f"  {prompt} [{default}]: ").strip()
        if raw == "":
            return default
        try:
            return int(raw)
        except ValueError:
            print("    ↳ enter a whole number.")


def ask_list(prompt: str, default: list[str] | None = None) -> list[str]:
    """Comma-separated list. Empty → default (or [])."""
    hint = f" [{', '.join(default)}]" if default else ""
    raw = input(f"  {prompt} (comma-separated){hint}: ").strip()
    if not raw:
        return list(default or [])
    return [item.strip() for item in raw.split(",") if item.strip()]


def section(title: str, blurb: str = "") -> None:
    print()
    print(f"── {title} " + "─" * max(0, 70 - len(title)))
    if blurb:
        print(f"   {blurb}")


# ───────────────────────────────────────────────────────────────────────
#  YAML emitter — clean, sectioned, hand-edit friendly
# ───────────────────────────────────────────────────────────────────────
SECTION_COMMENTS = {
    "service": "Identity metadata for the service.",
    "phoenix": "Where Airen reads prediction observability from.",
    "serving": "How the inference layer serves predictions (sync-api | async-kafka | batch).",
    "observation": "The Phoenix span schema Sentinel reads (error attribute, segments, metric type).",
    "github": "Where Investigator looks for code-level evidence.",
    "slack": "Where Airen posts alerts (alert_channel=null → use SLACK_CHANNEL env).",
    "jira": "Where Airen files / transitions incident tickets.",
    "sentinel": "Per-service health verdict tuning (when to WARN / CRITICAL).",
    "model_registry": "Each production model_family → its training provenance.",
    "mlflow": "Model registry / training-run lineage (FK VM; disabled by default).",
    "redshift": "Historical predictions / actuals for batch analysis (FK VM; disabled).",
    "s3": "Training-time baselines (s3://<bucket>/baselines/<service>/<ver>.json).",
    "kafka": "Peek-only live validation (FK VM; disabled by default).",
}

# Stable, human-friendly ordering of top-level blocks.
ORDER = [
    "service", "phoenix", "serving", "observation", "github", "slack", "jira",
    "sentinel", "model_registry", "mlflow", "redshift", "s3", "kafka",
]


def render_yaml(cfg: dict, service_name: str, *, generated_by: str = "python -m airen.run_onboard") -> str:
    lines = [
        f"# Airen service config for '{service_name}'.",
        f"# Generated by `{generated_by}`. Hand-edit freely.",
        "#",
        f"#   Loader: airen.config.load_service_config('{service_name}')",
        f"#   Runner: python -m airen.run_orchestrator {service_name}",
        "",
    ]
    for key in ORDER:
        if key not in cfg:
            continue
        comment = SECTION_COMMENTS.get(key)
        if comment:
            lines.append(f"# {comment}")
        block = yaml.safe_dump(
            {key: cfg[key]}, sort_keys=False, default_flow_style=False, allow_unicode=True
        ).rstrip()
        lines.append(block)
        lines.append("")
    return "\n".join(lines) + "\n"
